# -*- coding: utf-8 -*-
"""Sistem_Panen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k_jrR7G6mIx9RfbTamnLwHT5_J_RKBAT
"""

"""
Sistem Pencatatan Hasil Panen Digital
Berkas utama untuk mencatat data hasil panen petani.
"""

data_panen = []


def tambah_panen(nama_petani, komoditas, jumlah_kg, harga_per_kg):
    """Menambahkan satu catatan hasil panen ke dalam data_panen."""
    catatan = {
        "nama_petani": nama_petani,
        "komoditas": komoditas,
        "jumlah_kg": jumlah_kg,
        "harga_per_kg": harga_per_kg,
        "total": jumlah_kg * harga_per_kg,
    }
    data_panen.append(catatan)
    return catatan


def tampilkan_panen():
    """Menampilkan seluruh catatan hasil panen yang tersimpan."""
    for i, catatan in enumerate(data_panen, start=1):
        print(f"{i}. {catatan['nama_petani']} - {catatan['komoditas']} "
              f"- {catatan['jumlah_kg']} kg - Rp{catatan['total']:,.0f}")


if __name__ == "__main__":
    tambah_panen("Pak Slamet", "Padi", 500, 6000)
    tambah_panen("Bu Aminah", "Jagung", 300, 4500)
    tampilkan_panen()